export const FETCH_ARTICLES_REQUESTED = "FETCH_ARTICLES_REQUESTED";
export const FETCH_ARTICLES_SUCCEEDED = "FETCH_ARTICLES_SUCCEEDED";
export const FETCH_ARTICLES_FAILED = "FETCH_ARTICLES_FAILED";

export const FETCH_ARTICLE_BY_ID_REQUESTED = "FETCH_ARTICLE_BY_ID_REQUESTED";
export const FETCH_ARTICLE_BY_ID_SUCCEEDED = "FETCH_ARTICLE_BY_ID_SUCCEEDED";
export const FETCH_ARTICLE_BY_ID_FAILED = "FETCH_ARTICLE_BY_ID_FAILED";

export const ARTICLE_FIELDS_UPDATED = "ARTICLE_FIELDS_UPDATED";

export const POST_ARTICLE_REQUESTED = "POST_ARTICLE_REQUESTED";
export const POST_ARTICLE_SUCCEEDED = "POST_ARTICLE_SUCCEEDED";
export const POST_ARTICLE_FAILED = "POST_ARTICLE_FAILED";
export const POST_ARTICLE_ERRORED = "POST_ARTICLE_ERRORED";

export const RETURN_TO_HOME_BUTTON_CLICKED = "RETURN_TO_HOME_BUTTON_CLICKED";

export const CLOSE_ARTICLE_SUCCESS_BUTTON_CLICKED = "CLOSE_ARTICLE_SUCCESS_BUTTON_CLICKED";

export const POST_AUTHORIZATION_REQUESTED = "POST_AUTHORIZATION_REQUESTED";
export const POST_AUTHORIZATION_SUCCEEDED = "POST_AUTHORIZATION_SUCCEEDED";
export const POST_AUTHORIZATION_FAILED = "POST_AUTHORIZATION_FAILED";

export const SIGN_IN_FIELDS_UPDATED = "SIGN_IN_FIELDS_UPDATED";

export const CLOSE_AUTHORIZATION_FAILURE_BUTTON_CLICKED = "CLOSE_AUTHORIZATION_FAILURE_BUTTON_CLICKED";
export const SIGN_OUT_BUTTON_CLICKED = "SIGN_OUT_BUTTON_CLICKED";
